// <auto-generated />
using System;
using FidoDino.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace fidodino.Infrastructure.Data.Migrations
{
    [DbContext(typeof(FidoDinoDbContext))]
    partial class FidoDinoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FidoDino.Domain.Entities.Auth.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Auth.Permission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Auth.RolePermission", b =>
                {
                    b.Property<Guid>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderUserId")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Game.ActiveEffect", b =>
                {
                    b.Property<Guid>("ActiveEffectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EffectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ActiveEffectId");

                    b.HasIndex("EffectId");

                    b.HasIndex("GameSessionId");

                    b.ToTable("ActiveEffects");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Game.Effect", b =>
                {
                    b.Property<Guid>("EffectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("EffectType")
                        .HasColumnType("integer");

                    b.HasKey("EffectId");

                    b.ToTable("Effects");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Game.GameSession", b =>
                {
                    b.Property<Guid>("GameSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("GameSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Game.GameSessionSnapshot", b =>
                {
                    b.Property<Guid>("GameSessionSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("GameSessionSnapshotId");

                    b.ToTable("GameSessionSnapshots");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Game.Ice", b =>
                {
                    b.Property<Guid>("IceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("IceType")
                        .HasColumnType("integer");

                    b.Property<double>("Probability")
                        .HasColumnType("double precision");

                    b.Property<int>("RequiredShake")
                        .HasColumnType("integer");

                    b.HasKey("IceId");

                    b.ToTable("Ices");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Game.IceReward", b =>
                {
                    b.Property<Guid>("IceRewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IceId")
                        .HasColumnType("uuid");

                    b.Property<double>("Probability")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uuid");

                    b.HasKey("IceRewardId");

                    b.HasIndex("IceId");

                    b.HasIndex("RewardId");

                    b.ToTable("IceRewards");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Game.PlayTurn", b =>
                {
                    b.Property<Guid>("PlayTurnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EarnedScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uuid");

                    b.Property<int>("ShakeCount")
                        .HasColumnType("integer");

                    b.HasKey("PlayTurnId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("IceId");

                    b.HasIndex("RewardId");

                    b.ToTable("PlayTurns");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Game.Reward", b =>
                {
                    b.Property<Guid>("RewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EffectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RewardName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("RewardId");

                    b.HasIndex("EffectId");

                    b.ToTable("Rewards");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Leaderboard.LeaderboardSnapshot", b =>
                {
                    b.Property<Guid>("LeaderboardSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("TimeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeRange")
                        .HasColumnType("integer");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LeaderboardSnapshotId");

                    b.ToTable("LeaderboardSnapshots");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Leaderboard.LeaderboardState", b =>
                {
                    b.Property<Guid>("LeaderboardStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<string>("StableRandom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeRange")
                        .HasColumnType("integer");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LeaderboardStateId");

                    b.HasIndex("UserId");

                    b.ToTable("LeaderboardStates");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Leaderboard.ScoreEvent", b =>
                {
                    b.Property<Guid>("ScoreEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AppliedToRedis")
                        .HasColumnType("boolean");

                    b.Property<long?>("CompositeDelta")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScoreDelta")
                        .HasColumnType("integer");

                    b.Property<int>("TimeRange")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ScoreEventId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("ScoreEvents");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.System.SystemStatus", b =>
                {
                    b.Property<Guid>("SystemStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SystemStatusId");

                    b.ToTable("SystemStatuses");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Auth.PasswordResetToken", b =>
                {
                    b.HasOne("FidoDino.Domain.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.HasOne("FidoDino.Domain.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("FidoDino.Domain.Entities.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Game.ActiveEffect", b =>
                {
                    b.HasOne("FidoDino.Domain.Entities.Game.Effect", "Effect")
                        .WithMany("ActiveEffects")
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FidoDino.Domain.Entities.Game.GameSession", "GameSession")
                        .WithMany("ActiveEffects")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Effect");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Game.GameSession", b =>
                {
                    b.HasOne("FidoDino.Domain.Entities.Auth.User", "User")
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Game.IceReward", b =>
                {
                    b.HasOne("FidoDino.Domain.Entities.Game.Ice", "Ice")
                        .WithMany("IceRewards")
                        .HasForeignKey("IceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FidoDino.Domain.Entities.Game.Reward", "Reward")
                        .WithMany("IceRewards")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ice");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Game.PlayTurn", b =>
                {
                    b.HasOne("FidoDino.Domain.Entities.Game.GameSession", "GameSession")
                        .WithMany("PlayTurns")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FidoDino.Domain.Entities.Game.Ice", "Ice")
                        .WithMany()
                        .HasForeignKey("IceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FidoDino.Domain.Entities.Game.Reward", "Reward")
                        .WithMany()
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Ice");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Game.Reward", b =>
                {
                    b.HasOne("FidoDino.Domain.Entities.Game.Effect", "Effect")
                        .WithMany()
                        .HasForeignKey("EffectId");

                    b.Navigation("Effect");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Leaderboard.LeaderboardState", b =>
                {
                    b.HasOne("FidoDino.Domain.Entities.Auth.User", "User")
                        .WithMany("LeaderboardStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Leaderboard.ScoreEvent", b =>
                {
                    b.HasOne("FidoDino.Domain.Entities.Game.GameSession", "GameSession")
                        .WithMany()
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FidoDino.Domain.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Auth.User", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("LeaderboardStates");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Game.Effect", b =>
                {
                    b.Navigation("ActiveEffects");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Game.GameSession", b =>
                {
                    b.Navigation("ActiveEffects");

                    b.Navigation("PlayTurns");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Game.Ice", b =>
                {
                    b.Navigation("IceRewards");
                });

            modelBuilder.Entity("FidoDino.Domain.Entities.Game.Reward", b =>
                {
                    b.Navigation("IceRewards");
                });
#pragma warning restore 612, 618
        }
    }
}
